---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
  - name: download copy agent
    shell: curl https://copy.com/install/mac/Copy.dmg > ~/Downloads/Copy.dmg
  - name: extract copy agent
    shell: cd ~/Downloads; open Copy.dmg
