---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
# TODO: This could become a repeatable pattern...
  tasks:
#  - name: download copy agent
#   shell: curl https://copy.com/install/linux/Copy.tgz > ~/Downloads/Copy.tgz
  - name: extract copy agent
    shell: cd ~; tar xzvf ~/Downloads/Copy.tgz 
