---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: yes
  tasks:
  - name: i3 and related
    yum: pkg={{ item }} state=installed
    with_items: 
    - i3
    - conky
    - xscreensaver
    - xscreensaver-data-extra 
    - xscreensaver-gl-extra
#  - name: disable gnome-screensaver
#    shell: 
  - name: add xscreensaver to startup
    shell: touch ~/.xinitrc; echo "xscreensaver -no-splash" >> ~/.xinitrc

# echo "Disabling Gnome Screensaver"
# sudo killall gnome-screensaver
# gconftool-2 --type boolean -s /apps/gnome_settings_daemon/screensaver/start_screensaver false

# echo "Enable lock, if desired."
# xscreensaver-demo
