---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
#  - name: install brew
#    shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  - name: install packages with Brew
    shell: brew install {{ pkg }}
    with_items: 
    - maven
