---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
  - name: install packages with Brew
    shell: brew install {{ item }}
    with_items: 
    - ctags
    - bash-completion 
    - ssh-copy-id 
    - wget
