---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  sudo: no
  tasks:
  - name: install macvim
    shell: brew install macvim
  - name: install vim-anywhere
    shell: curl -fsSL https://raw.github.com/cknadler/vim-anywhere/master/install | bash
